### ISSUE TITLE
Error right after install

### ISSUE THREAD

**Issue by app-god** [acomagu/fish-async-prompt#62]
```
Standard input (line 10):
            set -f _pipestatus $line[2..]
            ^

(Type 'help set' for related documentation)
set: Unknown option '-f'
```

I'm guessing that I'm running an ancient form of fish. It's 3.3.1.

I'll probably just build from source, but it might be nice to let users know of minimum requirements--unless I'm missed something.

Really cool idea and I look forward to using it.

**Comment by BarbzYHOOL** [comment]
@acomagu I also have this issue and no idea what is happening, it seems like a very old error from 2014...
I'm also on 3.3.1

@app-god did you try a newer version of fish shell for this tho?

**Comment by faho** [comment]
`set -f` was introduced in fish 3.4.0.

Fish 3.3.1 is ~10% of all commits ever made to fish behind. If you want to upgrade, you can probably find repositories on https://fishshell.com/.

**Comment by BarbzYHOOL** [comment]
@faho I've found posts about "set -f" from 2014...
I also searched on that page https://fishshell.com/docs/3.4/relnotes.html#fish-3-4-0-released-march-12-2022 and found nothing related to `set -f`. Is it `set --function`??

You mean that fish 3.3.1 has 10% less commits than the current one? if so, that's crazy, 10% in one year o_0

But thanks, gonna update fish then

**Comment by faho** [comment]
>Is it set --function??

Yeah. See https://fishshell.com/docs/current/cmds/set.html.

>You mean that fish 3.3.1 has 10% less commits than the current one? if so, that's crazy, 10% in one year o_0

Yup. Fish was started 17 ago and 50% of all commits to it happened in the last ~4. Fish 3.0 is over 40% of commits behind.

**Comment by acomagu** [comment]
I'm sorry. I'll try to clarify the supported Fish version.

In addition, fish-async-prompt has been updated according to Fish updates, so an older version of fish-async-prompt is likely to be compatible with an older version of Fish.

**Comment by BarbzYHOOL** [comment]
> Yup. Fish was started 17 ago and 50% of all commits to it happened in the last ~4. Fish 3.0 is over 40% of commits behind.

Can you be clearer plz? missing words here I guess, I am very curious about this info!!

Thanks acomagu

**Comment by faho** [comment]
>Can you be clearer plz? missing words here I guess, I am very curious about this info!!

Fish's history leading up from the start of the git repository to the 3.5.1 tag consists of a total of 15836 commits (as determined by `git rev-list --count 3.5.1`). I.e. if you check the commit the tag refers to, and follow all of its parent commits until there is no more parent (the very first commit), you get 15836 commits.

By the same metric, fish 3.0.0 consists of 9169 (or 57% of 3.5.1), 2.7.1 consists of 7361 (46% of 3.5.1). That means 2.7.1 is missing 54% of 3.5.1's commits, and 3.0.0 is missing 43%, so the 50% mark was somewhere between the two, which was about 4 years ago.

(this is a bit simplified and could miscount backports and -merges, but fish doesn't really do those *much*, so it should be roughly accurate)

Here's a table:

|release|commits since previous release|percent of commits to 3.5.1 missing|date|
|:---|:---|:---|:---|
|3.5.1|24|0%|2022-07-20 18:15:47 +0800 (3 months ago)|
|3.5.0|433|0.2%|2022-06-16 21:02:33 +1000 (4 months ago)|
|3.4.1|9|2.9%|2022-03-26 00:27:56 +0800 (7 months ago)|
|3.4.0|1106|2.9%|2022-03-12 22:31:57 +0800 (8 months ago)|
|3.3.1|23|9.9%|2021-07-06 22:45:48 +0800 (1 year, 4 months ago)|
|3.3.0|435|10.1%|2021-06-28 22:47:23 +0800 (1 year, 4 months ago)|
|3.2.2|14|12.8%|2021-04-07 20:31:56 +0800 (1 year, 7 months ago)|
|3.2.1|75|12.9%|2021-03-18 11:06:08 +0800 (1 year, 7 months ago)|
|3.2.0|2177|13.4%|2021-03-01 20:47:21 +0800 (1 year, 8 months ago)|
|3.1.2|4|27.1%|2020-04-29 10:54:46 +0800 (2 years, 6 months ago)|
|3.1.1|87|27.2%|2020-04-27 22:06:32 +0800 (2 years, 6 months ago)|
|3.1.0|2210|27.7%|2020-02-12 22:04:14 +0800 (2 years, 8 months ago)|
|3.0.2|3|41.7%|2019-02-19 21:39:26 +0800 (3 years, 8 months ago)|
|3.0.1|67|41.7%|2019-02-11 20:15:06 +0800 (3 years, 8 months ago)|
|3.0.0|1808|42.1%|2018-12-28 21:01:25 +0800 (3 years, 10 months ago)|
|2.7.1|3|53.5%|2017-12-23 00:16:35 +0800 (4 years, 10 months ago)|
|2.7.0|418|53.5%|2017-11-23 13:45:56 +0800 (4 years, 11 months ago)|

Anyway, that's not really the point of this bug so I'll be leaving now.

Might help determine which fish versions are still worth supporting, I guess? But then OSen shipping with them and the features they add are probably more important.

**Comment by BarbzYHOOL** [comment]
Thanks

I tried on live install and on recent fish it worked (ofc)
