### ISSUE TITLE
`Expected a variable name after this $` error during installation

### ISSUE THREAD

**Issue by injust** [acomagu/fish-async-prompt#80]
Running:
```
$ fisher install acomagu/fish-async-prompt
```
Results in:
```
fish: Expected a variable name after this $.
```

Using `fish, version 3.7.1` and `fisher, version 4.4.4` on macOS Sonoma 14.5

**Comment by LRNZ09** [comment]
You should run the command without the dollar sign at the beginning. So, instead of typing `$ fisher install acomagu/fish-async-prompt`, just type `fisher install acomagu/fish-async-prompt`.

The dollar sign is typically used to indicate the command prompt in examples and shouldn't be included in the actual command.

**Comment by injust** [comment]
Ugh, I don't know how I didn't notice the `$` when I copy-pasted 😭

**Comment by injust** [comment]
Opened https://github.com/acomagu/fish-async-prompt/pull/81 because the `$` just makes copy-pasting harder IMO.
